# Site settings
title: Muntazir Fadhel
description: 'The Software Engineering Blog of Muntazir Fadhel'
url: 'www.mfadhel.com'
baseurl: '/'
google_analytics: 'UA-80543111-1'
disqus_shortname: 'MuntazirFadhel'
mailchimp_subscribe_page: https://mailchi.mp/c976e4a02c94/mfadhel


author:
  name: ''
  email: muntazirfadhel@gmail.com
  github_username: zir0-93
  linkedin_username: muntazirfadhel
  twitter_username: MuntazirFadhel
  img: /images/muntazir_fadhel.png

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
