# Site settings
title: Muntazir Fadhel
# description: 'www.mfadhel.com'
url: 'https://zir0-93.github.io'
baseurl: '/'
google_analytics: 'UA-80543111-1'
disqus_shortname: 'MuntazirFadhel'

author:
  name: ''
  email: muntazir@live.ca
  github_username: zir0-93
  linkedin_username: muntazirfadhel
  twitter_username: FadhelMuntazir

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 20
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
