# Site settings
title: The Clarity Views Blog
description: 'Clarity Views - how developers understand code'
url: 'https://clarity-team.github.io'
baseurl: '/'
google_analytics: 'UA-80543111-2'
disqus_shortname: 'clarity-team'

author:
  name: ''
  email: admin@clarityviews.com
  twitter_username: clarity_views
  facebook_username: clarityviews
  github_username:  clarity-team

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
